import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Listening English",
  description: "Generated by dungta",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="flex justify-center bg-gray-50 min-h-screen">
        <div className="w-full max-w-[430px] min-h-screen bg-white shadow-lg">
          {children}
        </div>
      </body>
    </html>
  );
}
